Add support for prefixes to the `FromHex` trait
rust-bitcoin/hex-conservative pull request #58
Opened 2024-01-08 04:57 UTC by tcharding

Add support for parsing prefixed strings as well as requiring the presence or absence of the prefix.

This code was copied from `rust-bitcoin`. The error type was re-named.

2024-01-08 14:36 UTC, apoelstra commented
concept ACK. I'd drop the bolding from "not" in "not recommended for user input".

2024-01-09 03:54 UTC, tcharding commented
Added a solution to the inner `String` error, WIP for feedback, probably falls in @Kixunil's wheelhouse.

2024-01-15 14:19 UTC, Kixunil reviewed
I was just writing an objection but I've just realized the `from_hex` method was wrong from the beginning of this crate. It changed the semantics of to allow `0x` which previously wasn't allowed causing everyone who used it to accidentally implement the broken "robustness" principle. While we've strictly issued breaking versions it's still subtle and people probably thought it's the same method.

Thankfully it didn't affect most of the hashes because of reversed handling. But it does affect `FromStr for Midstate`.

And since the robustness principle is broken, I would prefer changing the semantics of `from_hex` to what it originally was and use `from_maybe_prefixed_hex` for the current one.

Definitely concept ACK doing something about this.

2024-01-15 14:24 UTC, Kixunil commented
Regarding `InputString`, it was never intended to appear in stable public API and pulling in `bitcoin_internals` sucks for the same reason this crate is not called `bitcoin_hex`. So I suggest just creating `#[non_exhaustive] pub struct MissingPrefixError(#[cfg(feature = "alloc")] String);` and using that one in the variant.

2024-01-15 19:56 UTC, tcharding commented
> The main difference being that hex-encoded bytes never start with 0x prefix so trying to write that code would be silly/buggy.

Quote for #2323

I had definitely forgotten this, this is a simple discreet problem that we can fix. Leave it with me.

2024-02-12 11:27 UTC, Kixunil requested changes

2024-02-12 11:27 UTC, Kixunil commented on src/parse.rs
> +            Self::from_no_prefix_hex(s.as_ref().trim_start_matches("0x"))
`trim_start_matches` removes repeated matches so it allows `0x0x0x0x42`, which is wrong. Also the whole code seems to be needlessly complicated. You should only need this:

```rust
Self::from_no_prefix_hex(s.strip_prefix("0x").unwrap_or(s))
```

2024-02-12 11:27 UTC, Kixunil commented on src/parse.rs
> +        #[cfg(not(feature = "alloc"))] S: AsRef<str>,
This is broken because people can call the method for non-alloc and then alloc would silently add the bound.

2024-02-12 11:27 UTC, Kixunil commented on src/parse.rs
> +    /// It should be only used for existing protocols which always encode values as hex without 0x prefix.
There should be a note that this is equivalent to `from_hex` But maybe let's not duplicate the method?

2024-02-12 11:27 UTC, Kixunil commented on src/parse.rs
> +            Ok(Self::from_no_prefix_hex(s.as_ref().trim_start_matches("0x"))?)
Same problem as above, you can use `s.as_ref().strip_prefix("0x").ok_or_else(|| MissingPrefixError(s.into()).into())`

2024-02-12 23:17 UTC, tcharding commented
This PR is tied up with the `FromHex` error stuff.

2024-02-13 03:10 UTC, tcharding commented
Consumed by #67

2024-02-13 03:10 UTC, closed without merging