Introduce more serde utils
rust-bitcoin/hex-conservative pull request #92
Opened 2024-06-20 05:02 UTC by tcharding

Copy the `serde_utils` modules for ser/deser of `BTreeMap`s. Currently includes the `hex_bytes` module even though it would seem we don't need it but I couldn't get it to work with the current functions. Its private as opposed to the original where it was public.

2024-06-20 05:03 UTC, tcharding commented
If this lands we can use this to assist the crate smashing effort in `rust-bitcoin`. The new crates need these utils.

2024-06-22 17:28 UTC, apoelstra commented
To clarify -- you copied this from rust-bitcoin? Or from std?

2024-06-22 17:29 UTC, apoelstra commented
Ah, it's from rust-bitcoin. Cool.

2024-06-22 19:24 UTC, apoelstra commented
@tcharding can you update Cargo.toml to turn on the `derive` feature of `serde` even when it's not a dev-dependency?

I'm not sure why cargo seems to be OK with the current PR but it's technically incorrect and my local non-cargo tooling is breaking on it.

2024-06-23 23:57 UTC, tcharding commented
Added an additional patch up front.

2024-06-30 19:01 UTC, Kixunil requested changes
~~I believe the first commit is just plain wrong~~ (see below) and second has questionable usefulness.

Side note: I never intended for `hex-conservative` to be a dumping ground for random hex-related shit. I want it to be a nice idiomatic crate. Adding stuff that's only used in one crate until someone else needs it is not helpful to achieve this goal.

2024-06-30 19:08 UTC, Kixunil commented
> my local non-cargo tooling is breaking on it.

Oh, this PR causes it, it wasn't a problem before. Having it in two commits is confusing.

So if this is accepted I'd prefer to squash the commits since they don't make sense separated. That being said, adding another dependency for this is annoying, it'd be nice trying to impl it manually since it just uses `serialize_with` anyway.

2024-06-30 23:22 UTC, closed without merging

2024-07-01 01:10 UTC, apoelstra commented
> Side note: I never intended for `hex-conservative` to be a dumping ground for random hex-related shit

Should we start `bitcoin-hex` then with hex-related shit that we need for rust-bitcoin?

2024-07-01 03:09 UTC, Kixunil commented
This particular one is only needed for PSBT. If we need it for multiple things and multiple crates then that would be a strong indication that putting it into `hex-conservative` is actually worth it. (But we could let it sit for a bit in `internals`.)

2024-07-01 13:40 UTC, apoelstra commented
@tcharding is it only PSBT?

Actually, if it's really only PSBT then we can maybe get away with dropping the serde serialization entirely and just serializing as strings... I really dislike breaking serde de/serialization but this one is really ad-hoc.

2024-07-01 14:04 UTC, Kixunil commented
Exactly. Serialize as base64.

2024-07-02 04:08 UTC, tcharding commented
Used also in `witness`, I'll investigate if we can remove that.

bitcoin/src/blockdata/witness.rs:476:                seq.serialize_element(&crate::serde_utils::SerializeBytesAsHex(elem))?;

2024-07-02 04:34 UTC, Kixunil commented
Damn, I had a huge brain fart yesterday forgetting there's also `SerialzieBytesAsHex`. That one is generally useful I believe and should be added. Sorry about the noise.

2024-08-04 19:56 UTC, tcharding commented
For posterity, this was closed in favour of https://github.com/rust-bitcoin/hex-conservative/pull/96